spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: munan135
    url: jdbc:mysql://localhost:3306/db_example

## https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html